org: sunday
app: aws-node-express-api-project
service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev

functions:
  hello:
    handler: src/handler.genrateRandomeNumber
    timeout: 60 # seconds
    memorySize: 128 #mb